### PR TITLE
Added Protection to all the routes

### PR DESCRIPTION
**Pull request by mark-nakachon**
### Checklist:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [ ] Have you successfully ran tests with your changes locally?
* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?

### Issues Solved

Fixes #{99}

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
And please resolve conflicts.

**Comment by mark-nakachon** [comment]
Working on it bro

**Comment by mark-nakachon** [comment]
@aashutoshrathi lines 70-72 will be uncommented after creating a form that the user selects various options for modifying parameters  on the backend

**Comment by aashutoshrathi** [comment]
@rossoskull Please update the score for this PR. This is an `easy` one.

**Pull request merged**
