### PR TITLE
Remove input and output files after zipping

### LINKED ISSUE #2: Input and Output file should be deleted after zipping

### PR DESCRIPTION
**Pull request by gerardogalvez**
Fixes #2.

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Hi! Thanks for PR.
Make sure you have checked points in PR Template correctly.

**Comment by gerardogalvez** [comment]
Which template?

**Comment by aashutoshrathi** [comment]
Oh, Sorry haven't added PR Templates yet 😓

**Comment by aashutoshrathi** [comment]
Oh, Sorry haven't added PR Templates yet 😓

**Comment by aashutoshrathi** [comment]
Give new line at the end of everyfile and also try this on local and share a screenshot

**Comment by aashutoshrathi** [comment]
Feel free to star this repo and also respond Have you checked it locally?

**Comment by gerardogalvez** [comment]
Yes, l just need to add the newlines and take the screenshots.

**Comment by gerardogalvez** [comment]
I just added the newlines. Here's a gif of running the Python generator, it also works with the others.

**Pull request merged**
