### PR TITLE
Running python scripts as soon as user uploaded 

### PR DESCRIPTION
**Pull request by mark-nakachon**
### Checklist:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you successfully ran tests with your changes locally?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### Issues Solved

Fixes #{87}

### CODE REVIEW

**Comment by mark-nakachon** [comment]
Please review my pr

**Comment by aashutoshrathi** [comment]
PLEASE Rebase!!!

**Comment by mark-nakachon** [comment]
squashed commits

**Comment by aashutoshrathi** [comment]
Update your branch, it shows merged changes too.

**Comment by mark-nakachon** [comment]
After merging this PR I will delete this branch

**Comment by aashutoshrathi** [comment]
In any case, please update branch, that's for better diff.

**Comment by mark-nakachon** [comment]
SORRY i committed these changes accidentally please delete this PR i will make  a new PR

**Pull request closed without merging**
