### PR TITLE
Added zipping feature

### PR DESCRIPTION
**Pull request by mark-nakachon**
### Checklist:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you successfully ran tests with your changes locally?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### Issues Solved

Fixes #{96}

### CODE REVIEW

**Comment by mark-nakachon** [comment]
Please review my PR

**Comment by mark-nakachon** [comment]
Resolved conflicts

**Comment by mark-nakachon** [comment]
Please try to reproduce the steps provided in the GIF

**Comment by aashutoshrathi** [comment]
Do you understand that this PR changes a single line only?

**Comment by mark-nakachon** [comment]
No bro please check this it changes 9 lines in one commit and it adds another line in another commit

**Comment by mark-nakachon** [comment]
Screenshot from 2019-05-17 19-27-15

**Comment by mark-nakachon** [comment]
Screenshot from 2019-05-17 19-50-52
Screenshot from 2019-05-17 19-49-38

**Comment by mark-nakachon** [comment]
Please review the screen shots

**Comment by mark-nakachon** [comment]
> Any updates on this?

Please review the screenshots bro

**Comment by aashutoshrathi** [comment]
Sorry it doesn't work that way!

**Comment by rossoskull** [comment]
Try pulling the changes to your `zipping` branch, and view the diff.

**Comment by mark-nakachon** [comment]
This pull request actually sends a zip is generated on the server to the front end and I am able to do this on my local machine and I don't understand why it does not work for you guys

**Comment by rossoskull** [comment]
You can see here that you have made 8 commits, and only a single line is changed. So there definitely is a problem with your fork and this repository. Maybe you didn't branch correctly and pushed your changes specific to this PR in other PRs. We simply cannot merge without knowing what went wrong.

Screenshot from 2019-05-24 14-49-08

**Comment by mark-nakachon** [comment]
I will make another pr

**Pull request closed without merging**
