### PR TITLE
PR Template Updates

### LINKED ISSUE #19: PR Template Change
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Description

In PR Template,
```
### Issues Solved

[//]: # (List Issue Numbers)
```
needs to be changed to 
```
### Issues Solved

Fixes #{Issue Number}

[//]: # For eg. `Fixes #5`
```

### Required Information
- [x] Provide a **minimal code snippet** / example that reproduces the bug.
- [ ] Provide **screenshots** (if required)
- [x] Provide github **revision**

### PR DESCRIPTION
**Pull request by ItsPugle**
This push resolves/covers Issue #19. I've directly copied and pasted the suggestion over, but I have a few other ideas we can use instead of the copy-pasted snippet.

### Checklist:

* [ ] Have you followed the guidelines in our Contributing document? There's no contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ ] Have you successfully ran tests with your changes locally?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### Issues Solved
Fixes #19

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Hi! Thanks for PR.
Make sure you have checked points in PR Template correctly.

**Comment by ItsPugle** [comment]
We could possibly replace `[//]: # For eg. `Fixes #5`` wiht `[//]: Following the #, place the issue code from any related issue.`

**Comment by aashutoshrathi** [comment]
No, This Style is good.
Better change comment style from
`[//]: # Comments` to `<!-- Comments -->`

**Comment by ItsPugle** [comment]
Done @aashutoshrathi!

**Comment by ItsPugle** [comment]
Cheers!

**Pull request merged**
