### PR TITLE
Landing Page created

### LINKED ISSUE #60: Initiate WebApp's Frontend
Initiate a front end with landing page for the app.

### PR DESCRIPTION
**Pull request by raibove**
Created front-end with landing page

### Checklist:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you successfully ran tests with your changes locally?
* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?

### Issues Solved

Fixes #60

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Hi! Thanks for PR.
Make sure you have checked points in PR Template correctly.

(Powered by [GitMate.io](https://gitmate.io))

**Comment by raibove** [comment]
[img.docx](https://github.com/aashutoshrathi/HackerRank-Test-Case-Generator/files/3025097/img.docx)

Screenshot is in this file

**Comment by rossoskull** [comment]
@aashutoshrathi  should we close this PR due to inactivity?

**Comment by aashutoshrathi** [comment]
Yeah!

**Pull request closed without merging**
