### PR TITLE
Added endpoints to all links on homepage

### LINKED ISSUE #77: Give links to all endpoints on homepage
On https://tc-gen.herokuapp.com
i.e. The page to be redirected in /, should have links to all endpoints directly.
Eg: Upload File, Compile Files, Generate Testcases

### PR DESCRIPTION
**Pull request by mark-nakachon**
### Checklist:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [x] Have you successfully ran tests with your changes locally?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### Issues Solved

Fixes #77

### CODE REVIEW

**Comment by mark-nakachon** [comment]
ohh

**Comment by mark-nakachon** [comment]
I will update my fork after you merge this pull request

**Comment by mark-nakachon** [comment]
@aashutoshrathi I have a doubt will you count my contributions and send it to gssoc

**Comment by aashutoshrathi** [comment]
Yes @mark-nakachon

**Comment by mark-nakachon** [comment]
Screenshot from 2019-04-20 18-06-15

**Comment by mark-nakachon** [comment]
Please merge this PR and update my points in the points list

**Pull request merged**
